<a href="https://colab.research.google.com/github/raineragoge/DATA-LAKE/blob/main/datalake2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
# Creamos atajos para hacer que sea mucho más fácil y flexible trabajar.
# Además que es más fácil realizar futuros cambios.
PATH = "/content/data_lake/procesed/"
PATH_RAW = "/content/data_lake/raw/"

In [27]:
# Creamos todas las carpetas que vamos autilizar en el ejercicio.
import os

carpetas = [
    "/content/data_lake",
    "/content/data_lake/procesed",
    "/content/data_lake/raw",
    "/content/data_lake/COMPLETADO"
]

for carpeta in carpetas:
    os.makedirs(carpeta, exist_ok=True)

print("Carpetas creadas correctamente.")

Carpetas creadas correctamente.

In [28]:
# Leemos los archivos descargados previamente.
import pandas as pd

clientes = pd.read_csv(PATH_RAW + "customers.csv")

print(clientes)

   customer_id     name     city  age
0            1    Alice   Madrid   25
1            2      Bob  Chicago   34
2            3  Charlie   London   29
3            4    Diana  Chicago   41
4            5      Eve   Madrid   22
5            6    Frank   Berlin   37

In [29]:
# Leemos los archivos descargados previamente.
import pandas as pd

productos = pd.read_json(PATH_RAW + "productos.json")

print(productos)

   product_id     product     category  price
0         101      Laptop  Electronics   1200
1         102       Mouse  Accessories     25
2         103    Keyboard  Accessories     80
3         104     Monitor  Electronics    300
4         105  Headphones        Audio    150

In [30]:
# Limpiamos los archivos para que sean leibles por el programa. (cambiomos los "|" por ",")
import pandas as pd

pedidos = pd.read_csv(
    PATH_RAW + "orders.txt",
    sep="|",
    header=None,
    names=["order_id", "customer_id", "product_id", "quantity"]
)

pedidos.to_csv("orders.csv", index=False)

In [31]:
# Leemos los archivos descargados previamente.
import pandas as pd

productos = pd.read_json(PATH_RAW + "productos.json")

productos.to_csv("productos.csv", index=False)

print(productos)

   product_id     product     category  price
0         101      Laptop  Electronics   1200
1         102       Mouse  Accessories     25
2         103    Keyboard  Accessories     80
3         104     Monitor  Electronics    300
4         105  Headphones        Audio    150

In [32]:
# Unir pedidos con clientes por customer_id
datos = pedidos.merge(clientes, on="customer_id", how="left")

# Unir el resultado con productos por product_id
datos = datos.merge(productos, on="product_id", how="left")

# Guardar la tabla completa
datos.to_csv("filtadro.csv", index=False)

print(datos)

   order_id  customer_id  product_id  quantity     name     city  age  \
0      1001            1         101         1    Alice   Madrid   25
1      1002            2         102         2      Bob  Chicago   34
2      1003            1         103         1    Alice   Madrid   25
3      1004            3         104         2  Charlie   London   29
4      1005            4         101         1    Diana  Chicago   41
5      1006            5         105         2      Eve   Madrid   22
6      1007            6         103         3    Frank   Berlin   37
7      1008            2         105         1      Bob  Chicago   34

      product     category  price
0      Laptop  Electronics   1200
1       Mouse  Accessories     25
2    Keyboard  Accessories     80
3     Monitor  Electronics    300
4      Laptop  Electronics   1200
5  Headphones        Audio    150
6    Keyboard  Accessories     80
7  Headphones        Audio    150

In [33]:
# Guardar la tabla completa
datos.to_csv(PATH +"tabla_completa.csv", index=False)

print(datos)

   order_id  customer_id  product_id  quantity     name     city  age  \
0      1001            1         101         1    Alice   Madrid   25
1      1002            2         102         2      Bob  Chicago   34
2      1003            1         103         1    Alice   Madrid   25
3      1004            3         104         2  Charlie   London   29
4      1005            4         101         1    Diana  Chicago   41
5      1006            5         105         2      Eve   Madrid   22
6      1007            6         103         3    Frank   Berlin   37
7      1008            2         105         1      Bob  Chicago   34

      product     category  price
0      Laptop  Electronics   1200
1       Mouse  Accessories     25
2    Keyboard  Accessories     80
3     Monitor  Electronics    300
4      Laptop  Electronics   1200
5  Headphones        Audio    150
6    Keyboard  Accessories     80
7  Headphones        Audio    150

In [34]:
#Ejecutar la operación para saber los precios totales reales.
datos["total"] = datos["quantity"] * datos["price"]

In [35]:
#Guardar el CSV con la nueva columna
datos.to_csv(PATH +"total_sin_iva.csv", index=False)
print(datos)

   order_id  customer_id  product_id  quantity     name     city  age  \
0      1001            1         101         1    Alice   Madrid   25
1      1002            2         102         2      Bob  Chicago   34
2      1003            1         103         1    Alice   Madrid   25
3      1004            3         104         2  Charlie   London   29
4      1005            4         101         1    Diana  Chicago   41
5      1006            5         105         2      Eve   Madrid   22
6      1007            6         103         3    Frank   Berlin   37
7      1008            2         105         1      Bob  Chicago   34

      product     category  price  total
0      Laptop  Electronics   1200   1200
1       Mouse  Accessories     25     50
2    Keyboard  Accessories     80     80
3     Monitor  Electronics    300    600
4      Laptop  Electronics   1200   1200
5  Headphones        Audio    150    300
6    Keyboard  Accessories     80    240
7  Headphones        Audio    150    150

In [36]:
#Ejecutar la operación para saber los precios totales reales con iva
datos["con_iva"] = datos["total"] + ((datos["total"] * 0.21))

In [37]:
#Guardar el CSV con la nueva columna
datos.to_csv(PATH + "total_con_iva.csv", index=False)
print(datos)

   order_id  customer_id  product_id  quantity     name     city  age  \
0      1001            1         101         1    Alice   Madrid   25
1      1002            2         102         2      Bob  Chicago   34
2      1003            1         103         1    Alice   Madrid   25
3      1004            3         104         2  Charlie   London   29
4      1005            4         101         1    Diana  Chicago   41
5      1006            5         105         2      Eve   Madrid   22
6      1007            6         103         3    Frank   Berlin   37
7      1008            2         105         1      Bob  Chicago   34

      product     category  price  total  con_iva
0      Laptop  Electronics   1200   1200   1452.0
1       Mouse  Accessories     25     50     60.5
2    Keyboard  Accessories     80     80     96.8
3     Monitor  Electronics    300    600    726.0
4      Laptop  Electronics   1200   1200   1452.0
5  Headphones        Audio    150    300    363.0
6    Keyboard  Accessories     80    240    290.4
7  Headphones        Audio    150    150    181.5

In [38]:
# Eliminar columna city
df = pd.DataFrame(datos)
datos = df.drop(['city'], axis=1)

In [39]:
#Guardar el CSV con la nueva columna
datos.to_csv(PATH + "eliminar_city.csv", index=False)
print(datos)

   order_id  customer_id  product_id  quantity     name  age     product  \
0      1001            1         101         1    Alice   25      Laptop
1      1002            2         102         2      Bob   34       Mouse
2      1003            1         103         1    Alice   25    Keyboard
3      1004            3         104         2  Charlie   29     Monitor
4      1005            4         101         1    Diana   41      Laptop
5      1006            5         105         2      Eve   22  Headphones
6      1007            6         103         3    Frank   37    Keyboard
7      1008            2         105         1      Bob   34  Headphones

      category  price  total  con_iva
0  Electronics   1200   1200   1452.0
1  Accessories     25     50     60.5
2  Accessories     80     80     96.8
3  Electronics    300    600    726.0
4  Electronics   1200   1200   1452.0
5        Audio    150    300    363.0
6  Accessories     80    240    290.4
7        Audio    150    150    181.5

In [40]:
# Edad mayor que 30:
df.loc[df["age"] >= 30]

,order_id,customer_id,product_id,quantity,name,city,age,product,category,price,total,con_iva
1,1002,2,102,2,Bob,Chicago,34,Mouse,Accessories,25,50,60.5
4,1005,4,101,1,Diana,Chicago,41,Laptop,Electronics,1200,1200,1452.0
6,1007,6,103,3,Frank,Berlin,37,Keyboard,Accessories,80,240,290.4
7,1008,2,105,1,Bob,Chicago,34,Headphones,Audio,150,150,181.5

In [41]:
# Edad menor que 30:
df.loc[df["age"] < 30]

,order_id,customer_id,product_id,quantity,name,city,age,product,category,price,total,con_iva
0,1001,1,101,1,Alice,Madrid,25,Laptop,Electronics,1200,1200,1452.0
2,1003,1,103,1,Alice,Madrid,25,Keyboard,Accessories,80,80,96.8
3,1004,3,104,2,Charlie,London,29,Monitor,Electronics,300,600,726.0
5,1006,5,105,2,Eve,Madrid,22,Headphones,Audio,150,300,363.0

In [42]:
# Ordenar los datos según el valor de IVA
datos_ordenados = datos.sort_values(by="con_iva")

In [43]:
# Ordenar los datos según el valor de IVA de mayor a menor
datos_ordenados = datos.sort_values(by="con_iva", ascending=False)

In [44]:
datos_ordenados.to_csv(PATH + "datos_ordenados.csv", index=False)
print(datos_ordenados)

   order_id  customer_id  product_id  quantity     name  age     product  \
0      1001            1         101         1    Alice   25      Laptop
4      1005            4         101         1    Diana   41      Laptop
3      1004            3         104         2  Charlie   29     Monitor
5      1006            5         105         2      Eve   22  Headphones
6      1007            6         103         3    Frank   37    Keyboard
7      1008            2         105         1      Bob   34  Headphones
2      1003            1         103         1    Alice   25    Keyboard
1      1002            2         102         2      Bob   34       Mouse

      category  price  total  con_iva
0  Electronics   1200   1200   1452.0
4  Electronics   1200   1200   1452.0
3  Electronics    300    600    726.0
5        Audio    150    300    363.0
6  Accessories     80    240    290.4
7        Audio    150    150    181.5
2  Accessories     80     80     96.8
1  Accessories     25     50     60.5

In [45]:
#Guardar los datos finales completados:
datos_ordenados.to_csv("/content/data_lake/COMPLETADO/completado.csv", index=False)
print(datos_ordenados)

   order_id  customer_id  product_id  quantity     name  age     product  \
0      1001            1         101         1    Alice   25      Laptop
4      1005            4         101         1    Diana   41      Laptop
3      1004            3         104         2  Charlie   29     Monitor
5      1006            5         105         2      Eve   22  Headphones
6      1007            6         103         3    Frank   37    Keyboard
7      1008            2         105         1      Bob   34  Headphones
2      1003            1         103         1    Alice   25    Keyboard
1      1002            2         102         2      Bob   34       Mouse

      category  price  total  con_iva
0  Electronics   1200   1200   1452.0
4  Electronics   1200   1200   1452.0
3  Electronics    300    600    726.0
5        Audio    150    300    363.0
6  Accessories     80    240    290.4
7        Audio    150    150    181.5
2  Accessories     80     80     96.8
1  Accessories     25     50     60.5

In [46]:
import pandas as pd
pd.read_csv("/content/data_lake/COMPLETADO/completado.csv")

,order_id,customer_id,product_id,quantity,name,age,product,category,price,total,con_iva
0,1001,1,101,1,Alice,25,Laptop,Electronics,1200,1200,1452.0
1,1005,4,101,1,Diana,41,Laptop,Electronics,1200,1200,1452.0
2,1004,3,104,2,Charlie,29,Monitor,Electronics,300,600,726.0
3,1006,5,105,2,Eve,22,Headphones,Audio,150,300,363.0
4,1007,6,103,3,Frank,37,Keyboard,Accessories,80,240,290.4
5,1008,2,105,1,Bob,34,Headphones,Audio,150,150,181.5
6,1003,1,103,1,Alice,25,Keyboard,Accessories,80,80,96.8
7,1002,2,102,2,Bob,34,Mouse,Accessories,25,50,60.5

In [48]:
 # Requerimientos para poder usar la extensión "parquet".
!pip install pandas pyarrow

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.13/dist-packages (23.0.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [49]:
# Crear carpeta parquet
import os

ruta = os.path.join("/content/data_lake/COMPLETADO", "completado.parquet")

datos_ordenados.to_parquet(ruta, engine="pyarrow", index=False)
print(datos_ordenados)

   order_id  customer_id  product_id  quantity     name  age     product  \
0      1001            1         101         1    Alice   25      Laptop
4      1005            4         101         1    Diana   41      Laptop
3      1004            3         104         2  Charlie   29     Monitor
5      1006            5         105         2      Eve   22  Headphones
6      1007            6         103         3    Frank   37    Keyboard
7      1008            2         105         1      Bob   34  Headphones
2      1003            1         103         1    Alice   25    Keyboard
1      1002            2         102         2      Bob   34       Mouse

      category  price  total  con_iva
0  Electronics   1200   1200   1452.0
4  Electronics   1200   1200   1452.0
3  Electronics    300    600    726.0
5        Audio    150    300    363.0
6  Accessories     80    240    290.4
7        Audio    150    150    181.5
2  Accessories     80     80     96.8
1  Accessories     25     50     60.5